[package]
name = "otrr"
version = "0.1.0"
authors = ["Danny van Heumen <danny@dannyvanheumen.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4"
base64 = "0.13.0"
